project:
  type: website
  output-dir: docs
  resources:
    - "data"

website:
  repo-url: https://github.com/inqs909/ttw
  title: "TTW"
  site-url: www.inqs.info/ttw

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

editor: source

